#application: claslite
application: claslite-prototype
#version: stable
#version: v01
version: test
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: pycrypto
  version: "2.3"
- name: django
  version: "1.2"


default_expiration: "5d"

builtins:
- remote_api: on
- deferred: on

inbound_services:
- warmup

skip_files:
- config.rb
- Gemfile
- ^(.*/)?.*\.swp$
- static/bb
- content/css
- ^(.*/)?.*\.sqlite$

error_handlers:
- file: templates/error_handlers/default_error.html

- error_code: over_quota
  file: templates/error_handlers/over_quota.html

- error_code: dos_api_denial
  file: templates/error_handlers/dos_api_denial.html

- error_code: timeout
  file: templates/error_handlers/timeout.html

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /(robots\.txt|.*\.html|css/.*|images/.*|js/.*)
  static_files: static/\1
  upload: static/(.*)

- url: /static
  static_dir: static

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: .*
  script: main.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
